<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <IsPackable>true</IsPackable>
        <Title>Velopack Bootstrapper</Title>
        <Authors>Luke Lanphear</Authors>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
         <PackageReference Include="Velopack" Version="1.2.0" />
    </ItemGroup>

</Project>
